### ISSUE TITLE
Code uses part of visual search

### ISSUE THREAD

**Issue by pjankiewicz** [xueyc1f/d4ocr-rust#1]
I searched for some onnx code in Rust and noticed you took the code from my project https://github.com/recoai/visual-search/blob/master/src/image_transform/pipeline.rs without any credit to my project.

Please provide a link to my project if you are using it especially without mentioning the license.

**Comment by xueyc1f** [comment]
> I searched for some onnx code in Rust and noticed you took the code from my project https://github.com/recoai/visual-search/blob/master/src/image_transform/pipeline.rs without any credit to my project.
> 
> Please provide a link to my project if you are using it especially without mentioning the license.

ok, I'm added your porject link in readme，this is just a learning demo, thank you for your project
